/* ============================================================
   TRAINING DATA  ·  "Project Absolute Unit"
   Verbatim transcription of every level table from the PDF.
   Do not edit casually — the progression system depends on
   array lengths and order. LV n = index n-1.
   ============================================================ */

const RITUAL_LEVELS = [
  /* LV1 */  { hang: "Dead hang 10 s", push: "3 wall push-ups", squat: "5 sit-to-stands", core: "20 s dead bug", shoulders: "10 arm circles each way" },
  /* LV2 */  { hang: "Dead hang 15 s", push: "5 wall push-ups", squat: "8 sit-to-stands", core: "30 s dead bug", shoulders: "15 arm circles" },
  /* LV3 */  { hang: "Dead hang 20 s", push: "8 wall push-ups", squat: "10 sit-to-stands", core: "20 s tucked hollow", shoulders: "15 arm circles" },
  /* LV4 */  { hang: "Dead hang 25 s", push: "5 high incline push-ups", squat: "10 bodyweight squats", core: "25 s tucked hollow", shoulders: "10 wall slides" },
  /* LV5 */  { hang: "Dead hang 30 s", push: "8 high incline push-ups", squat: "12 bodyweight squats", core: "30 s tucked hollow", shoulders: "12 wall slides" },
  /* LV6 */  { hang: "Active hang 5\u00d73 s", push: "10 high incline push-ups", squat: "15 bodyweight squats", core: "30 s one-leg hollow", shoulders: "12 wall slides" },
  /* LV7 */  { hang: "Active hang 5\u00d75 s", push: "6 mid incline push-ups", squat: "15 bodyweight squats", core: "20 s full hollow", shoulders: "10 lateral raises 1 kg" },
  /* LV8 */  { hang: "5 scapular pull-ups", push: "8 mid incline push-ups", squat: "18 bodyweight squats", core: "25 s full hollow", shoulders: "12 lateral raises 1 kg" },
  /* LV9 */  { hang: "8 scapular pull-ups", push: "10 mid incline push-ups", squat: "20 bodyweight squats", core: "30 s full hollow", shoulders: "12 lateral raises 1.5 kg" },
  /* LV10 */ { hang: "10 scapular pull-ups", push: "6 low incline push-ups", squat: "8 split squats/side", core: "35 s full hollow", shoulders: "12 lateral raises 1.5 kg" },
  /* LV11 */ { hang: "Dead hang 40 s", push: "8 low incline push-ups", squat: "10 split squats/side", core: "40 s full hollow", shoulders: "12 lateral raises 2 kg" },
  /* LV12 */ { hang: "Dead hang 50 s", push: "10 low incline push-ups", squat: "12 split squats/side", core: "20 s side plank/side", shoulders: "12 lateral raises 2 kg" },
  /* LV13 */ { hang: "Dead hang 60 s", push: "5 knee push-ups", squat: "12 split squats/side", core: "25 s side plank/side", shoulders: "12 rear delt flies 2 kg" },
  /* LV14 */ { hang: "10 scapular pull-ups + 30 s hang", push: "8 knee push-ups", squat: "15 squats + 10 s hold", core: "30 s side plank/side", shoulders: "12 rear delt flies 2 kg" },
  /* LV15 */ { hang: "12 scapular pull-ups", push: "12 knee push-ups", squat: "20 squats + 15 s hold", core: "45 s full hollow", shoulders: "12 lateral raises 2.5 kg" },
  /* LV16 */ { hang: "Towel hang 20 s", push: "5 full push-ups", squat: "8 Bulgarian split squats/side", core: "10 hollow rocks", shoulders: "12 lateral raises 2.5 kg" },
  /* LV17 */ { hang: "Towel hang 30 s", push: "8 full push-ups", squat: "10 Bulgarian split squats/side", core: "15 hollow rocks", shoulders: "12 lateral raises 3 kg" },
  /* LV18 */ { hang: "5 slow negative pull-ups", push: "10 full push-ups", squat: "12 Bulgarian split squats/side", core: "20 hollow rocks", shoulders: "12 lateral raises 3 kg" },
  /* LV19 */ { hang: "3 pull-ups (easy)", push: "12 full push-ups", squat: "15 Bulgarian split squats/side", core: "10 hanging knee raises", shoulders: "12 rear delt flies 3 kg" },
  /* LV20 */ { hang: "4 pull-ups (easy)", push: "15 full push-ups", squat: "8 assisted pistols/side", core: "15 hanging knee raises", shoulders: "12 lateral raises 3.5 kg" },
  /* LV21 */ { hang: "5 pull-ups (easy)", push: "8 deficit push-ups", squat: "10 assisted pistols/side", core: "20 hanging knee raises", shoulders: "12 lateral raises 3.5 kg" },
  /* LV22 */ { hang: "5 pull-ups + 20 s hang", push: "10 deficit push-ups", squat: "10 reverse nordics", core: "15 s tuck L-sit", shoulders: "12 lateral raises 4 kg" },
  /* LV23 */ { hang: "6 pull-ups (easy)", push: "12 deficit push-ups", squat: "12 reverse nordics", core: "20 s tuck L-sit", shoulders: "12 lateral raises 4 kg" },
  /* LV24 */ { hang: "6 pull-ups + towel hang 30 s", push: "8 decline push-ups", squat: "12 reverse nordics", core: "15 s L-sit", shoulders: "12 lateral raises 4.5 kg" },
  /* LV25 */ { hang: "8 pull-ups (easy)", push: "12 decline push-ups", squat: "15 reverse nordics", core: "20 s L-sit", shoulders: "12 lateral raises 5 kg" },
];

const RITUAL_SLOT_ORDER = ["hang", "push", "squat", "core", "shoulders"];
const RITUAL_SLOT_NAMES = { hang: "Hang", push: "Push", squat: "Squat", core: "Core", shoulders: "Shoulders" };
const RITUAL_MVD = "Minimum Viable Dose: one dead hang + five squats (40 seconds). Counts as a completed day.";

const TRACKS = {
  t1: { name: "T1 Vertical Pull", short: "T1 Pull", levels: [
    { ex: "Dead hang", target: "2 \u00d7 10 s" },
    { ex: "Dead hang", target: "3 \u00d7 15 s" },
    { ex: "Dead hang", target: "3 \u00d7 25 s" },
    { ex: "Active hang", target: "3 \u00d7 5 s" },
    { ex: "Active hang", target: "3 \u00d7 12 s" },
    { ex: "Scapular pull-up", target: "3 \u00d7 5" },
    { ex: "Scapular pull-up", target: "3 \u00d7 8" },
    { ex: "Scapular pull-up, 2 s hold at top", target: "3 \u00d7 8" },
    { ex: "Inverted row, bar at chest height (very upright)", target: "3 \u00d7 8" },
    { ex: "Inverted row, chest height", target: "3 \u00d7 15" },
    { ex: "Inverted row, bar at waist height", target: "3 \u00d7 8" },
    { ex: "Inverted row, waist height", target: "3 \u00d7 15" },
    { ex: "Inverted row, bar at hip height", target: "3 \u00d7 8" },
    { ex: "Inverted row, hip height", target: "3 \u00d7 15" },
    { ex: "Inverted row, feet elevated on chair", target: "3 \u00d7 8" },
    { ex: "Inverted row, feet elevated", target: "3 \u00d7 12" },
    { ex: "Inverted row, feet elevated, 2 s pause at top", target: "3 \u00d7 10" },
    { ex: "Jump to top of pull-up, hold chin over bar", target: "3 \u00d7 5 s" },
    { ex: "Jump to top, hold", target: "3 \u00d7 12 s" },
    { ex: "Negative pull-up, 3 s lower", target: "3 \u00d7 3" },
    { ex: "Negative pull-up, 5 s lower", target: "3 \u00d7 3" },
    { ex: "Negative pull-up, 8 s lower", target: "3 \u00d7 3" },
    { ex: "Assisted chin-up, both feet on chair", target: "3 \u00d7 5" },
    { ex: "Assisted chin-up, one foot on chair", target: "3 \u00d7 5" },
    { ex: "Chin-up, unassisted", target: "3 \u00d7 1" },
    { ex: "Chin-up", target: "3 \u00d7 3" },
    { ex: "Chin-up", target: "3 \u00d7 5" },
    { ex: "Pull-up, unassisted", target: "3 \u00d7 1" },
    { ex: "Pull-up", target: "3 \u00d7 3" },
    { ex: "Pull-up", target: "3 \u00d7 5" },
    { ex: "Pull-up", target: "3 \u00d7 7" },
    { ex: "Pull-up", target: "3 \u00d7 9" },
    { ex: "Pull-up, 1 s pause at top", target: "3 \u00d7 8" },
    { ex: "Wide-grip pull-up", target: "3 \u00d7 5" },
    { ex: "Wide-grip pull-up", target: "3 \u00d7 8" },
    { ex: "Weighted pull-up, vest +2.5 kg", target: "3 \u00d7 5" },
    { ex: "Weighted pull-up, +5 kg", target: "3 \u00d7 5" },
    { ex: "Weighted pull-up, +7.5 kg", target: "3 \u00d7 5" },
    { ex: "Explosive pull-up, chest to bar", target: "3 \u00d7 5" },
    { ex: "Weighted pull-up, +10 kg", target: "3 \u00d7 5" },
    { ex: "Commando pull-up", target: "3 \u00d7 5/side" },
    { ex: "Archer pull-up", target: "3 \u00d7 3/side" },
    { ex: "Typewriter pull-up", target: "3 \u00d7 3/side" },
    { ex: "Weighted pull-up, +20 kg or L-sit pull-up", target: "3 \u00d7 5" },
    { ex: "One-arm pull-up path: OA hang \u2192 OA scapular pull \u2192 towel-assisted OAP \u2192 OAP negative \u2192 OAP", target: "Own progression, years" },
  ]},
  t2: { name: "T2 Lever / Horizontal Pull", short: "T2 Lever", levels: [
    { ex: "Inverted row, chest height, 2 s pause", target: "3 \u00d7 10" },
    { ex: "Inverted row, waist height, 2 s pause", target: "3 \u00d7 10" },
    { ex: "Inverted row, hip height, 2 s pause", target: "3 \u00d7 10" },
    { ex: "Inverted row, feet elevated", target: "3 \u00d7 10" },
    { ex: "Straight-arm hanging scapular pullover", target: "3 \u00d7 8" },
    { ex: "Tuck hang (knees to chest, hanging)", target: "3 \u00d7 15 s" },
    { ex: "Tuck hang", target: "3 \u00d7 30 s" },
    { ex: "Skin the cat, partial (to shoulder height)", target: "3 \u00d7 3" },
    { ex: "Skin the cat, full", target: "3 \u00d7 3" },
    { ex: "German hang", target: "3 \u00d7 10 s" },
    { ex: "German hang", target: "3 \u00d7 25 s" },
    { ex: "Tuck front lever (back flat and horizontal)", target: "3 \u00d7 5 s" },
    { ex: "Tuck front lever", target: "3 \u00d7 10 s" },
    { ex: "Tuck front lever", target: "4 \u00d7 15 s" },
    { ex: "Tuck front lever", target: "4 \u00d7 20 s" },
    { ex: "Tuck front lever", target: "4 \u00d7 30 s" },
    { ex: "One-leg tuck front lever", target: "3 \u00d7 8 s/side" },
    { ex: "One-leg tuck front lever", target: "3 \u00d7 15 s/side" },
    { ex: "Advanced tuck front lever", target: "3 \u00d7 5 s" },
    { ex: "Advanced tuck front lever", target: "3 \u00d7 10 s" },
    { ex: "Advanced tuck front lever", target: "4 \u00d7 15 s" },
    { ex: "Advanced tuck front lever", target: "4 \u00d7 20 s" },
    { ex: "Advanced tuck front lever", target: "4 \u00d7 30 s" },
    { ex: "One-leg advanced tuck front lever", target: "3 \u00d7 8 s/side" },
    { ex: "One-leg advanced tuck front lever", target: "3 \u00d7 15 s/side" },
    { ex: "Wide straddle front lever (135\u00b0 legs)", target: "3 \u00d7 5 s" },
    { ex: "Wide straddle front lever", target: "3 \u00d7 12 s" },
    { ex: "Moderate straddle front lever (90\u00b0 legs)", target: "3 \u00d7 8 s" },
    { ex: "Moderate straddle front lever", target: "3 \u00d7 15 s" },
    { ex: "Narrow straddle front lever", target: "3 \u00d7 10 s" },
    { ex: "Half lay front lever (knees bent 90\u00b0)", target: "3 \u00d7 5 s" },
    { ex: "Half lay front lever", target: "3 \u00d7 12 s" },
    { ex: "Full front lever", target: "3 \u00d7 3 s" },
    { ex: "Full front lever", target: "3 \u00d7 8 s" },
    { ex: "Full front lever", target: "3 \u00d7 15 s" },
    { ex: "Tuck front lever row", target: "3 \u00d7 5" },
    { ex: "Advanced tuck front lever row", target: "3 \u00d7 5" },
    { ex: "Touch front lever raise, tuck", target: "3 \u00d7 5" },
    { ex: "Straddle front lever row", target: "3 \u00d7 5" },
    { ex: "Full front lever row", target: "3 \u00d7 3" },
  ]},
  t3: { name: "T3 Horizontal Push", short: "T3 Push", levels: [
    { ex: "Wall push-up", target: "2 \u00d7 8" },
    { ex: "Wall push-up", target: "3 \u00d7 15" },
    { ex: "Incline push-up, hands at chest height", target: "3 \u00d7 8" },
    { ex: "Incline push-up, chest height", target: "3 \u00d7 15" },
    { ex: "Incline push-up, hands at waist height", target: "3 \u00d7 8" },
    { ex: "Incline push-up, waist height", target: "3 \u00d7 15" },
    { ex: "Incline push-up, hands at hip height", target: "3 \u00d7 8" },
    { ex: "Incline push-up, hip height", target: "3 \u00d7 15" },
    { ex: "Incline push-up, hands at knee height", target: "3 \u00d7 8" },
    { ex: "Incline push-up, knee height", target: "3 \u00d7 15" },
    { ex: "Knee push-up", target: "3 \u00d7 10" },
    { ex: "Knee push-up, 3 s lower", target: "3 \u00d7 8" },
    { ex: "Negative push-up, 5 s lower", target: "3 \u00d7 5" },
    { ex: "Push-up", target: "3 \u00d7 3" },
    { ex: "Push-up", target: "3 \u00d7 6" },
    { ex: "Push-up", target: "3 \u00d7 10" },
    { ex: "Push-up", target: "3 \u00d7 15" },
    { ex: "Push-up", target: "3 \u00d7 20" },
    { ex: "Tempo push-up, 3 s down + 1 s bottom pause", target: "3 \u00d7 10" },
    { ex: "Deficit push-up (hands on handles)", target: "3 \u00d7 8" },
    { ex: "Deficit push-up", target: "3 \u00d7 15" },
    { ex: "Decline push-up, feet on chair", target: "3 \u00d7 10" },
    { ex: "Decline push-up", target: "3 \u00d7 15" },
    { ex: "Deficit decline push-up", target: "3 \u00d7 10" },
    { ex: "Weighted push-up, vest +5 kg", target: "3 \u00d7 12" },
    { ex: "Weighted push-up, +10 kg", target: "3 \u00d7 12" },
    { ex: "Dip support hold", target: "3 \u00d7 20 s" },
    { ex: "Dip support hold", target: "3 \u00d7 45 s" },
    { ex: "Dip negative, 5 s lower", target: "3 \u00d7 5" },
    { ex: "Dip", target: "3 \u00d7 3" },
    { ex: "Dip", target: "3 \u00d7 6" },
    { ex: "Dip", target: "3 \u00d7 10" },
    { ex: "Dip, full depth, 1 s pause at bottom", target: "3 \u00d7 8" },
    { ex: "Dip", target: "3 \u00d7 15" },
    { ex: "Weighted dip, +5 kg", target: "3 \u00d7 8" },
    { ex: "Weighted dip, +10 kg", target: "3 \u00d7 8" },
    { ex: "Weighted dip, +15 kg", target: "3 \u00d7 8" },
    { ex: "Weighted dip, +20 kg", target: "3 \u00d7 6" },
    { ex: "Weighted dip, +30 kg", target: "3 \u00d7 5" },
    { ex: "Pseudo-planche push-up", target: "3 \u00d7 8" },
    { ex: "Archer push-up", target: "3 \u00d7 5/side" },
    { ex: "One-arm push-up, hands at chest height", target: "3 \u00d7 5/side" },
    { ex: "One-arm push-up, hands at hip height", target: "3 \u00d7 5/side" },
    { ex: "One-arm negative, 5 s, on floor", target: "3 \u00d7 3/side" },
    { ex: "One-arm push-up, floor", target: "3 \u00d7 3/side" },
  ]},
  t4a: { name: "T4a Vertical Push", short: "T4a V-Push", levels: [
    { ex: "Incline pike push-up, hands at chest height", target: "3 \u00d7 8" },
    { ex: "Incline pike push-up, chest height", target: "3 \u00d7 15" },
    { ex: "Incline pike push-up, waist height", target: "3 \u00d7 8" },
    { ex: "Incline pike push-up, waist height", target: "3 \u00d7 15" },
    { ex: "Incline pike push-up, hip height", target: "3 \u00d7 10" },
    { ex: "Incline pike push-up, knee height", target: "3 \u00d7 10" },
    { ex: "Pike push-up, floor", target: "3 \u00d7 5" },
    { ex: "Pike push-up", target: "3 \u00d7 8" },
    { ex: "Pike push-up", target: "3 \u00d7 12" },
    { ex: "Pike push-up, 3 s lower", target: "3 \u00d7 8" },
    { ex: "Deficit pike push-up (hands on handles)", target: "3 \u00d7 5" },
    { ex: "Deficit pike push-up", target: "3 \u00d7 10" },
    { ex: "Deficit pike push-up", target: "3 \u00d7 15" },
    { ex: "Feet-elevated pike push-up (feet on chair)", target: "3 \u00d7 5" },
    { ex: "Feet-elevated pike push-up", target: "3 \u00d7 10" },
    { ex: "Feet-elevated pike push-up", target: "3 \u00d7 15" },
    { ex: "Deficit feet-elevated pike push-up", target: "3 \u00d7 5" },
    { ex: "Deficit feet-elevated pike push-up", target: "3 \u00d7 10" },
    { ex: "Wall walk", target: "3 \u00d7 3" },
    { ex: "Wall handstand, belly to wall", target: "3 \u00d7 20 s" },
    { ex: "Wall handstand", target: "3 \u00d7 40 s" },
    { ex: "Wall handstand", target: "3 \u00d7 60 s" },
    { ex: "Handstand shrug at wall", target: "3 \u00d7 8" },
    { ex: "Wall handstand push-up negative, 5 s", target: "3 \u00d7 3" },
    { ex: "Wall handstand push-up", target: "3 \u00d7 3" },
    { ex: "Wall handstand push-up", target: "3 \u00d7 6" },
    { ex: "Wall handstand push-up", target: "3 \u00d7 10" },
    { ex: "Deficit wall handstand push-up", target: "3 \u00d7 5" },
    { ex: "Deficit wall handstand push-up", target: "3 \u00d7 8" },
    { ex: "Freestanding handstand kick-up practice", target: "5 min, 10 attempts" },
    { ex: "Freestanding handstand", target: "3 \u00d7 10 s" },
    { ex: "Freestanding handstand", target: "3 \u00d7 30 s" },
    { ex: "Freestanding handstand", target: "1 \u00d7 60 s" },
    { ex: "Freestanding handstand push-up negative", target: "3 \u00d7 3" },
    { ex: "Freestanding handstand push-up", target: "3 \u00d7 3" },
  ]},
  t4b: { name: "T4b Side Delts", short: "T4b Delts", levels: [
    { ex: "Lateral raise 1.0 kg", target: "3 \u00d7 12, 3 s lower" },
    { ex: "Lateral raise 1.5 kg", target: "3 \u00d7 12, 3 s lower" },
    { ex: "Lateral raise 2.0 kg", target: "3 \u00d7 12, 3 s lower" },
    { ex: "Lateral raise 2.5 kg", target: "3 \u00d7 12, 3 s lower" },
    { ex: "Lateral raise 3.0 kg", target: "3 \u00d7 12, 3 s lower" },
    { ex: "Lateral raise 3.5 kg", target: "3 \u00d7 12, 3 s lower" },
    { ex: "Lateral raise 4.0 kg", target: "3 \u00d7 12, 3 s lower" },
    { ex: "Lateral raise 4.5 kg", target: "3 \u00d7 12, 3 s lower" },
    { ex: "Lateral raise 5.0 kg", target: "3 \u00d7 12, 3 s lower" },
    { ex: "Lateral raise 5.5 kg", target: "3 \u00d7 12, 3 s lower" },
    { ex: "Lateral raise 6.0 kg", target: "3 \u00d7 12, 3 s lower" },
    { ex: "Lateral raise 6.5 kg", target: "3 \u00d7 12, 3 s lower" },
    { ex: "Lateral raise 7.0 kg", target: "3 \u00d7 12, 3 s lower" },
    { ex: "Lateral raise 7.5 kg", target: "3 \u00d7 12, 3 s lower" },
    { ex: "Lateral raise 8.0 kg", target: "3 \u00d7 12, 3 s lower" },
    { ex: "Lateral raise 8.5 kg", target: "3 \u00d7 12, 3 s lower" },
    { ex: "Lateral raise 9.0 kg", target: "3 \u00d7 12, 3 s lower" },
    { ex: "Lateral raise 9.5 kg", target: "3 \u00d7 12, 3 s lower" },
    { ex: "Lateral raise 10.0 kg", target: "3 \u00d7 12, 3 s lower" },
    { ex: "Lateral raise 10.0 kg", target: "3 \u00d7 20, 3 s lower" },
  ]},
  t5: { name: "T5 Legs", short: "T5 Legs", levels: [
    { ex: "Sit-to-stand from chair", target: "2 \u00d7 8" },
    { ex: "Sit-to-stand", target: "3 \u00d7 15" },
    { ex: "Bodyweight squat", target: "3 \u00d7 10" },
    { ex: "Bodyweight squat", target: "3 \u00d7 20" },
    { ex: "Squat, 3 s down + 2 s pause at bottom", target: "3 \u00d7 10" },
    { ex: "Squat, deep, hands overhead", target: "3 \u00d7 15" },
    { ex: "Reverse lunge", target: "3 \u00d7 8/side" },
    { ex: "Reverse lunge", target: "3 \u00d7 15/side" },
    { ex: "Split squat", target: "3 \u00d7 10/side" },
    { ex: "Split squat, 3 s down", target: "3 \u00d7 10/side" },
    { ex: "Isometric hamstring bridge, two legs", target: "3 \u00d7 45 s" },
    { ex: "Isometric hamstring bridge, one leg", target: "3 \u00d7 20 s/side" },
    { ex: "Bulgarian split squat", target: "3 \u00d7 5/side" },
    { ex: "Bulgarian split squat", target: "3 \u00d7 10/side" },
    { ex: "Bulgarian split squat", target: "3 \u00d7 15/side" },
    { ex: "Bulgarian split squat, +5 kg dumbbells", target: "3 \u00d7 10/side" },
    { ex: "Bulgarian split squat, +10 kg", target: "3 \u00d7 10/side" },
    { ex: "Bulgarian split squat, vest +15 kg", target: "3 \u00d7 10/side" },
    { ex: "Squat, vest +20 kg", target: "3 \u00d7 15" },
    { ex: "Assisted pistol squat (two-hand support)", target: "3 \u00d7 5/side" },
    { ex: "Assisted pistol squat (one-hand support)", target: "3 \u00d7 8/side" },
    { ex: "Box pistol squat to chair", target: "3 \u00d7 5/side" },
    { ex: "Box pistol squat to low box", target: "3 \u00d7 8/side" },
    { ex: "Pistol squat negative, 5 s", target: "3 \u00d7 3/side" },
    { ex: "Pistol squat", target: "3 \u00d7 3/side" },
    { ex: "Pistol squat", target: "3 \u00d7 6/side" },
    { ex: "Pistol squat, +5 kg", target: "3 \u00d7 5/side" },
    { ex: "Pistol squat, +10 kg", target: "3 \u00d7 5/side" },
    { ex: "Pistol squat, vest +20 kg", target: "3 \u00d7 5/side" },
    { ex: "Reverse nordic, shallow lean", target: "3 \u00d7 8" },
    { ex: "Reverse nordic, medium lean", target: "3 \u00d7 10" },
    { ex: "Reverse nordic, full", target: "3 \u00d7 10" },
    { ex: "Reverse nordic, +5 kg vest", target: "3 \u00d7 10" },
    { ex: "Nordic curl negative, top third only", target: "3 \u00d7 5" },
    { ex: "Nordic curl negative, two thirds", target: "3 \u00d7 5" },
    { ex: "Nordic curl negative, full, 5 s", target: "3 \u00d7 3" },
    { ex: "Nordic curl, full rep", target: "3 \u00d7 3" },
    { ex: "Single-leg Romanian deadlift, +10 kg", target: "3 \u00d7 12/side" },
    { ex: "Single-leg calf raise off step", target: "3 \u00d7 15/side" },
    { ex: "Single-leg calf raise, vest +20 kg", target: "3 \u00d7 15/side" },
  ]},
  t6: { name: "T6 Core", short: "T6 Core", levels: [
    { ex: "Dead bug", target: "2 \u00d7 5/side" },
    { ex: "Dead bug", target: "3 \u00d7 10/side" },
    { ex: "Tucked hollow hold", target: "3 \u00d7 15 s" },
    { ex: "Tucked hollow hold", target: "3 \u00d7 30 s" },
    { ex: "One-leg extended hollow hold", target: "3 \u00d7 20 s/side" },
    { ex: "Hollow hold, arms at sides", target: "3 \u00d7 20 s" },
    { ex: "Full hollow hold, arms overhead", target: "3 \u00d7 15 s" },
    { ex: "Full hollow hold", target: "3 \u00d7 30 s" },
    { ex: "Full hollow hold", target: "3 \u00d7 45 s" },
    { ex: "Hollow rocks", target: "3 \u00d7 15" },
    { ex: "Plank", target: "3 \u00d7 60 s" },
    { ex: "Side plank", target: "3 \u00d7 45 s/side" },
    { ex: "Hanging knee raise", target: "3 \u00d7 8" },
    { ex: "Hanging knee raise", target: "3 \u00d7 15" },
    { ex: "Hanging knee raise, 3 s lower", target: "3 \u00d7 10" },
    { ex: "Tuck L-sit on bars", target: "3 \u00d7 10 s" },
    { ex: "Tuck L-sit", target: "3 \u00d7 25 s" },
    { ex: "One-leg extended L-sit", target: "3 \u00d7 10 s/side" },
    { ex: "L-sit on bars", target: "3 \u00d7 8 s" },
    { ex: "L-sit", target: "3 \u00d7 15 s" },
    { ex: "L-sit", target: "3 \u00d7 30 s" },
    { ex: "Hanging L-sit", target: "3 \u00d7 10 s" },
    { ex: "Hanging L-sit", target: "3 \u00d7 20 s" },
    { ex: "Hanging straight leg raise", target: "3 \u00d7 5" },
    { ex: "Hanging straight leg raise", target: "3 \u00d7 10" },
    { ex: "Toes-to-bar", target: "3 \u00d7 5" },
    { ex: "Toes-to-bar", target: "3 \u00d7 10" },
    { ex: "Toes-to-bar, 3 s lower", target: "3 \u00d7 8" },
    { ex: "Tuck dragon flag", target: "3 \u00d7 8 s" },
    { ex: "Tuck dragon flag", target: "3 \u00d7 20 s" },
    { ex: "Advanced tuck dragon flag", target: "3 \u00d7 8 s" },
    { ex: "Advanced tuck dragon flag", target: "3 \u00d7 20 s" },
    { ex: "One-leg dragon flag", target: "3 \u00d7 10 s/side" },
    { ex: "Straddle dragon flag", target: "3 \u00d7 10 s" },
    { ex: "Full dragon flag negative, 5 s", target: "3 \u00d7 3" },
    { ex: "Full dragon flag hold", target: "3 \u00d7 5 s" },
    { ex: "Full dragon flag reps", target: "3 \u00d7 3" },
    { ex: "Full dragon flag reps", target: "3 \u00d7 6" },
    { ex: "Hanging leg raise, vest +5 kg", target: "3 \u00d7 10" },
    { ex: "Windshield wipers hanging", target: "3 \u00d7 5/side" },
  ]},
  t7hang: { name: "T7 Grip \u2014 Hang", short: "T7 Hang", levels: [
    { ex: "Dead hang", target: "3 \u00d7 15 s" },
    { ex: "Dead hang", target: "3 \u00d7 30 s" },
    { ex: "Dead hang", target: "3 \u00d7 45 s" },
    { ex: "Dead hang", target: "3 \u00d7 60 s" },
    { ex: "Dead hang", target: "2 \u00d7 90 s" },
    { ex: "Towel hang", target: "3 \u00d7 20 s" },
    { ex: "Towel hang", target: "3 \u00d7 40 s" },
    { ex: "Towel hang", target: "3 \u00d7 60 s" },
    { ex: "Weighted hang +5 kg", target: "3 \u00d7 30 s" },
    { ex: "Weighted hang +10 kg", target: "3 \u00d7 30 s" },
    { ex: "Weighted hang +15 kg", target: "3 \u00d7 30 s" },
    { ex: "Weighted hang +20 kg", target: "3 \u00d7 30 s" },
    { ex: "Weighted hang +30 kg", target: "3 \u00d7 20 s" },
    { ex: "One-arm assisted hang", target: "3 \u00d7 15 s/side" },
    { ex: "One-arm hang", target: "3 \u00d7 10 s/side" },
    { ex: "One-arm hang", target: "3 \u00d7 20 s/side" },
    { ex: "One-arm hang", target: "3 \u00d7 30 s/side" },
    { ex: "One-arm towel hang", target: "3 \u00d7 10 s/side" },
    { ex: "False grip hang", target: "3 \u00d7 15 s" },
    { ex: "False grip hang", target: "3 \u00d7 30 s" },
    { ex: "False grip hang", target: "3 \u00d7 45 s" },
    { ex: "False grip inverted row", target: "3 \u00d7 8" },
    { ex: "False grip pull-up", target: "3 \u00d7 3" },
    { ex: "One-arm hang, vest +10 kg", target: "3 \u00d7 10 s/side" },
    { ex: "One-arm hang, vest +20 kg", target: "3 \u00d7 10 s/side" },
  ]},
  t7roller: { name: "T7 Grip \u2014 Wrist Roller", short: "T7 Roller", levels: [
    { ex: "Roller 2.5 kg", target: "2 rolls \u00d73" },
    { ex: "Roller 2.5 kg", target: "3 rolls \u00d73" },
    { ex: "Roller 5 kg", target: "2 rolls \u00d73" },
    { ex: "Roller 5 kg", target: "3 rolls \u00d73" },
    { ex: "Roller 7.5 kg", target: "2 rolls \u00d73" },
    { ex: "Roller 7.5 kg", target: "3 rolls \u00d73" },
    { ex: "Roller 10 kg", target: "2 rolls \u00d73" },
    { ex: "Roller 10 kg", target: "3 rolls \u00d73" },
    { ex: "Roller 12.5 kg", target: "2 rolls \u00d73" },
    { ex: "Roller 12.5 kg", target: "3 rolls \u00d73" },
    { ex: "Roller 15 kg", target: "2 rolls \u00d73" },
    { ex: "Roller 15 kg", target: "3 rolls \u00d73" },
    { ex: "Roller 17.5 kg", target: "3 rolls \u00d73" },
    { ex: "Roller 20 kg", target: "2 rolls \u00d73" },
    { ex: "Roller 20 kg", target: "3 rolls \u00d73" },
    { ex: "Roller 22.5 kg", target: "3 rolls \u00d73" },
    { ex: "Roller 25 kg", target: "2 rolls \u00d73" },
    { ex: "Roller 25 kg", target: "3 rolls \u00d73" },
    { ex: "Roller 27.5 kg", target: "3 rolls \u00d73" },
    { ex: "Roller 30 kg", target: "2 rolls \u00d73" },
    { ex: "Roller 30 kg", target: "3 rolls \u00d73" },
    { ex: "Roller 30 kg", target: "4 rolls \u00d73" },
    { ex: "Roller 30 kg", target: "5 rolls \u00d73" },
    { ex: "Reverse-grip roller 15 kg", target: "3 rolls" },
    { ex: "Reverse-grip roller 25 kg", target: "3 rolls" },
  ]},
};

/* Session types. "tracks" order = training order in the session. */
const SESSIONS = {
  pullA: { name: "PULL A", tracks: ["t1", "t2", "t7hang"], quota: true },
  pushA: { name: "PUSH A", tracks: ["t3", "t4a", "t4b"], quota: true },
  legs:  { name: "LEGS + CORE", tracks: ["t5", "t6", "t7roller"], quota: true },
  pullB: { name: "PULL/PUSH B", tracks: ["t1", "t3", "t6"], quota: true },
  pushB: { name: "PUSH B (optional 5th)", tracks: ["t4a", "t4b", "t5"], quota: false },
};

/* Weekly plan = the quota queue, in suggested order. Days are NOT fixed. */
const WEEK_PLAN_STAGE1 = ["pullA", "pushA", "legs", "pullB"];   // 4 sessions
const WEEK_PLAN_STAGE0 = ["pullA", "pushA"];                     // 2 sessions (conditioning phase)

/* Sanity checks — loudly complain if a table has the wrong length. */
(function () {
  const expect = { t1: 45, t2: 40, t3: 45, t4a: 35, t4b: 20, t5: 40, t6: 40, t7hang: 25, t7roller: 25 };
  console.assert(RITUAL_LEVELS.length === 25, "RITUAL_LEVELS must have 25 entries, has " + RITUAL_LEVELS.length);
  for (const [k, n] of Object.entries(expect)) {
    console.assert(TRACKS[k] && TRACKS[k].levels.length === n,
      "TRACKS." + k + " must have " + n + " levels, has " + (TRACKS[k] ? TRACKS[k].levels.length : "none"));
  }
})();
